### ISSUE TITLE
When processing a block with several instructions where only the last one is syntactically invalid, all of them are marked in red

### ISSUE THREAD

**Issue by jhjourdan** [psteckler/ProofGeneral#97]
Consider the follwoing coq code:

```
Class C : Type := {}.

Lemma C -> True.
```

Then C-c C-b.

Both instructions are shown in red. But only the second one is invalid.

**Comment by psteckler** [comment]
PG/xml was using a bad heuristic to know where to mark errors given in a fail-value, when in fact, the exact span was available. I've pushed that change.

Please verify the change works.

**Comment by jhjourdan** [comment]
This works, thanks!

**Comment by jhjourdan** [comment]
Still, there is still an issue: now, it seems like it is no longer possible to send to Coq something that appears after a syntax error.

Would it be possible to have some kind of heuristic to solve this issue in most of the cases ?

**Comment by jhjourdan** [comment]
Another issue: processing a large file seems much slower now because of the round-trip between emacs and Coq that happens at each command.

**Comment by psteckler** [comment]
Can you provide code demonstrating the can't-send-after-an-error?

The change for this bug should not have made anything slower. Do you have timings for a specific piece of code?

**Comment by jhjourdan** [comment]
I was thinking of something like:

```
Goal True. trivial. Qed.
Goal True. rewite -> 1. Qed.
Goal True. trivial. Qed.
```

However, I have tried with CoqIde, and it seems like it is neither able to send the `Goal True. trivial. Qed.`. So I'm not sure my wishes are really legitimate here.

**Comment by jhjourdan** [comment]
> The change for this bug should not have made anything slower. Do you have timings for a specific piece of code?

Ok, so that might be an illusion. Anyway, this is not the most important. So we can forget about that.

**Comment by psteckler** [comment]
> I was thinking of something like:

The syntax error in the second statement results in Coq responding with a fail-value, and both PG/xml and CoqIDE do a retract when they receive a fail-value. So the behavior you see is expected.

Other kinds of errors generate a success-value, and the error is flagged by a feedback. In that case, PG/xml and CoqIDE can proceed past the error, and just mark it red.
